services:
  conceptdigger:
    build: .
    ports:
      - "5007:5007"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - CACHE_FILE_PATH=data/wiki_data.json
    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "5007"
      - --reload
      - --reload-dir
      - app